[project]
name = "finalproject-garamov-26-555"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nikita Garamov", email = "garamovn@mail.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "prettytable>=3.18.0",
]

[project.scripts]
finalproject-garamov-26-555 = "finalproject_garamov_26_555:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.10",
]
